import { Product, Category } from './types';

// These mock products mirror the WooCommerce API structure
// Replace the image paths with the actual paths in the public directory once mapped.

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 1,
    name: 'Magnetic GPS Trackers',
    slug: 'magnetic-gps-trackers',
    parent: 0,
    description: 'Trackers with strong magnets for easy installation.',
    display: 'default',
    image: null,
    menu_order: 1,
    count: 3,
  },
  {
    id: 2,
    name: '4G GPS Trackers',
    slug: '4g-gps-trackers',
    parent: 0,
    description: '4G LTE wired GPS trackers for vehicles, fleets and asset management.',
    display: 'default',
    image: null,
    menu_order: 2,
    count: 1,
  },
  {
    id: 3,
    name: 'Personal GPS Trackers',
    slug: 'personal-gps-trackers',
    parent: 0,
    description: 'Portable GPS trackers for personal safety.',
    display: 'default',
    image: null,
    menu_order: 3,
    count: 1,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 101,
    name: 'Multi-Function Magnet GPS Tracker â€” 10000mAh',
    slug: 'magnet-gps-tracker-10000mah',
    permalink: 'https://aurogps.com/product/magnet-gps-tracker-10000mah',
    date_created: '2023-01-01T00:00:00',
    date_modified: '2023-01-01T00:00:00',
    type: 'simple',
    status: 'publish',
    featured: true,
    catalog_visibility: 'visible',
    description: '<p>Ideal for Vehicles, Logistics, Two Wheelers, Containers, Valuables, Construction Equipment, Generators, Trailers & More.</p>',
    short_description: '<p>Real-time tracking with 10000mAh battery for extended life. Strong magnet, voice listen, geo-fence, IP67 waterproof.</p>',
    sku: 'MAG-10000',
    price: '99.00',
    regular_price: '99.00',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_to: null,
    on_sale: false,
    purchasable: true,
    total_sales: 150,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 50,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: '0.5',
    dimensions: { length: '10', width: '5', height: '3' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '5.00',
    rating_count: 12,
    related_ids: [102, 103],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      { id: 1, name: 'Magnetic GPS Trackers', slug: 'magnetic-gps-trackers' },
    ],
    tags: [],
    images: [
      {
        id: 1,
        date_created: '2023-01-01T00:00:00',
        date_modified: '2023-01-01T00:00:00',
        src: '/images/products/mag-10000-main.jpg',
        name: 'Multi-Function Magnet GPS Tracker â€” 10000mAh Brochure',
        alt: 'AURO GPS Multi-Function Magnet GPS Tracker 10000mAh',
      },
      {
        id: 2,
        date_created: '2023-01-01T00:00:00',
        date_modified: '2023-01-01T00:00:00',
        src: '/images/products/mag-battery-compare.jpg',
        name: 'Battery Size Comparison 10000mAh vs 6000mAh vs 3000mAh',
        alt: 'Magnet GPS Tracker battery size comparison',
      },
    ],
    attributes: [
      {
        id: 1,
        name: 'Battery',
        position: 0,
        visible: true,
        variation: false,
        options: ['10000mAh'],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
  },
  {
    id: 102,
    name: 'Multi-Function Magnet GPS Tracker â€” 6000mAh',
    slug: 'magnet-gps-tracker-6000mah',
    permalink: 'https://aurogps.com/product/magnet-gps-tracker-6000mah',
    date_created: '2023-01-01T00:00:00',
    date_modified: '2023-01-01T00:00:00',
    type: 'simple',
    status: 'publish',
    featured: true,
    catalog_visibility: 'visible',
    description: '<p>Magnet GPS Tracker with Voice Listen Feature. Ideal for vehicles, logistics, two wheelers, containers, valuables and more.</p>',
    short_description: '<p>Real-time tracking with 6000mAh battery and voice listen feature.</p>',
    sku: 'MAG-6000',
    price: '79.00',
    regular_price: '89.00',
    sale_price: '79.00',
    date_on_sale_from: null,
    date_on_sale_to: null,
    on_sale: true,
    purchasable: true,
    total_sales: 200,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 100,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: '0.4',
    dimensions: { length: '8', width: '4', height: '2.5' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.8',
    rating_count: 24,
    related_ids: [101, 103],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      { id: 1, name: 'Magnetic GPS Trackers', slug: 'magnetic-gps-trackers' },
    ],
    tags: [],
    images: [
      {
        id: 3,
        date_created: '2023-01-01T00:00:00',
        date_modified: '2023-01-01T00:00:00',
        src: '/images/products/mag-6000-main.jpg',
        name: 'Magnet GPS Tracker with Voice Listen â€” 6000mAh Brochure',
        alt: 'AURO GPS Magnet GPS Tracker 6000mAh with Voice Listen Feature',
      },
      {
        id: 4,
        date_created: '2023-01-01T00:00:00',
        date_modified: '2023-01-01T00:00:00',
        src: '/images/products/mag-battery-compare.jpg',
        name: 'Battery Size Comparison',
        alt: 'Battery size comparison: 10000mAh, 6000mAh, 3000mAh',
      },
    ],
    attributes: [
      {
        id: 1,
        name: 'Battery',
        position: 0,
        visible: true,
        variation: false,
        options: ['6000mAh'],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
  },
  {
    id: 103,
    name: 'Multi-Function Magnet GPS Tracker â€” 3000mAh',
    slug: 'magnet-gps-tracker-3000mah',
    permalink: 'https://aurogps.com/product/magnet-gps-tracker-3000mah',
    date_created: '2023-01-01T00:00:00',
    date_modified: '2023-01-01T00:00:00',
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description: '<p>Ideal for Vehicles, Logistics, Two Wheelers, Containers, Valuables, Construction Equipment, Generators, Trailers & More.</p>',
    short_description: '<p>Compact real-time tracking with 3000mAh battery. Strong magnet, geo-fence, FOTA updates.</p>',
    sku: 'MAG-3000',
    price: '59.00',
    regular_price: '59.00',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_to: null,
    on_sale: false,
    purchasable: true,
    total_sales: 80,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 30,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: '0.3',
    dimensions: { length: '6', width: '4', height: '2' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.5',
    rating_count: 8,
    related_ids: [101, 102],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      { id: 1, name: 'Magnetic GPS Trackers', slug: 'magnetic-gps-trackers' },
    ],
    tags: [],
    images: [
      {
        id: 5,
        date_created: '2023-01-01T00:00:00',
        date_modified: '2023-01-01T00:00:00',
        src: '/images/products/mag-3000-main.jpg',
        name: 'Multi-Function Magnet GPS Tracker â€” 3000mAh Brochure',
        alt: 'AURO GPS Multi-Function Magnet GPS Tracker 3000mAh',
      },
      {
        id: 6,
        date_created: '2023-01-01T00:00:00',
        date_modified: '2023-01-01T00:00:00',
        src: '/images/products/mag-battery-compare.jpg',
        name: 'Battery Size Comparison',
        alt: 'Battery size comparison: 10000mAh, 6000mAh, 3000mAh',
      },
    ],
    attributes: [
      {
        id: 1,
        name: 'Battery',
        position: 0,
        visible: true,
        variation: false,
        options: ['3000mAh'],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
  },
  {
    id: 104,
    name: 'AURO 4G GPS Tracker',
    slug: 'auro-4g-gps-tracker',
    permalink: 'https://aurogps.com/product/auro-4g-gps-tracker',
    date_created: '2023-01-01T00:00:00',
    date_modified: '2023-01-01T00:00:00',
    type: 'simple',
    status: 'publish',
    featured: true,
    catalog_visibility: 'visible',
    description: '<p>Smart Tracking. Total Control. Features 4G LTE Connectivity, Real-time Tracking, One-way Voice Monitoring, Ignition (ACC) Detection, Speeding Alarm, Movement Alarm, Power Cut Alarm, Remote Fuel / Electricity Cut-off, APP & Web Tracking, Built-in Backup Battery, High GPS Accuracy, GT06 Protocol Support, Easy Installation.</p>',
    short_description: '<p>Advanced 4G wired GPS tracker with remote cut-off, voice monitoring & fleet management support.</p>',
    sku: 'AURO-4G',
    price: '49.00',
    regular_price: '49.00',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_to: null,
    on_sale: false,
    purchasable: true,
    total_sales: 500,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 150,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: '0.2',
    dimensions: { length: '5', width: '3', height: '1.5' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.9',
    rating_count: 55,
    related_ids: [106],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      { id: 2, name: '4G GPS Trackers', slug: '4g-gps-trackers' },
    ],
    tags: [],
    images: [
      {
        id: 7,
        date_created: '2023-01-01T00:00:00',
        date_modified: '2023-01-01T00:00:00',
        src: '/images/products/auro-4g-main.jpg',
        name: 'AURO 4G GPS Tracker Feature Brochure',
        alt: 'AURO 4G GPS Tracker â€” Smart Tracking, Total Control',
      },
      {
        id: 8,
        date_created: '2023-01-01T00:00:00',
        date_modified: '2023-01-01T00:00:00',
        src: '/images/products/auro-4g-device.jpg',
        name: 'AURO 4G GPS Tracker Device Photo',
        alt: 'AURO 4G GPS Tracker wired device with cables',
      },
      {
        id: 9,
        date_created: '2023-01-01T00:00:00',
        date_modified: '2023-01-01T00:00:00',
        src: '/images/products/auro-4g-sim.jpg',
        name: 'AURO 4G GPS Tracker with SIM Card',
        alt: 'AURO 4G GPS Tracker package with 1 year Airtel SIM card',
      },
      {
        id: 10,
        date_created: '2023-01-01T00:00:00',
        date_modified: '2023-01-01T00:00:00',
        src: '/images/products/auro-4g-uses.jpg',
        name: 'Smart Safety For Everyone â€” Use Cases',
        alt: 'AURO GPS 4G Tracker use cases for school children, factory workers, mining workers',
      },
    ],
    attributes: [
      {
        id: 2,
        name: 'Voltage',
        position: 0,
        visible: true,
        variation: false,
        options: ['9V - 90V DC'],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
  },
  {
    id: 105,
    name: 'Children / Students ID Card',
    slug: 'children-students-id-card',
    permalink: 'https://aurogps.com/product/children-students-id-card',
    date_created: '2023-01-01T00:00:00',
    date_modified: '2023-01-01T00:00:00',
    type: 'simple',
    status: 'publish',
    featured: true,
    catalog_visibility: 'visible',
    description: '<p>4G GPS tracker in an ID card format for children and students with real-time location tracking, SOS alerts and geofencing.</p>',
    short_description: '<p>4G GPS tracker in an ID card format for children and students with real-time location tracking, SOS alerts and geofencing.</p>',
    sku: 'CHILD-ID-001',
    price: '4500.00',
    regular_price: '6000.00',
    sale_price: '4500.00',
    date_on_sale_from: null,
    date_on_sale_to: null,
    on_sale: true,
    purchasable: true,
    total_sales: 60,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 20,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: '0.1',
    dimensions: { length: '4', width: '2.5', height: '0.5' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '5.0',
    rating_count: 5,
    related_ids: [],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      { id: 4, name: 'Kids & Student Trackers', slug: 'kids-student-trackers' },
    ],
    tags: [],
    images: [
      {
        id: 11,
        date_created: '2023-01-01T00:00:00',
        date_modified: '2023-01-01T00:00:00',
        src: '/images/products/children-id-card.png',
        name: 'Children / Students ID Card',
        alt: 'Children / Students ID Card tracker',
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
  },
];
export interface Solution {
  id: string;
  title: string;
  slug: string;
  shortDescription: string;
  content: string[];
  features: string[];
}

export const SOLUTIONS_DATA: Solution[] = [
  {
    id: 'fleet-management',
    title: 'Fleet Management Software',
    slug: 'fleet-management',
    shortDescription: 'Trakzee is a smart fleet management software that helps businesses track vehicles, monitor fuel, and improve driver safety.',
    content: [
      'Beyond track & trace: Transformative fleet management, not just location tracking',
      '365-day product enhancement: Continuous updates adapting to market changes',
      'Full customization: Your fleet, your rules â€” customization at its core',
      'Complimentary apps: Driver app & Technician app for seamless operations',
      'Scalable solutions: Different versions for all fleet sizes & business requirements'
    ],
    features: [
      'Fuel monitoring',
      'Video telematics',
      'Tire management',
      'Job management',
      'Driving behavior',
      'Elock',
      'Vehicle inspection',
      'Expense management',
      'Trailer tracking',
      'Load monitoring',
      'ADAS & DMS',
      'Route optimization'
    ]
  },
  {
    id: 'school-bus-tracking',
    title: 'School Bus Tracking Software',
    slug: 'school-bus-tracking',
    shortDescription: 'SmartBus solves school transportation issues with live tracking, optimized routes, and instant notifications.',
    content: [
      'White-labeling & customization: Customized brandable solution for system integrators & transport providers',
      'Accurate ETA: Accurate estimated time of arrival to plan pickups and drops',
      'Route optimization: Reduce travel time and fuel costs with better route planning',
      'Attendance marking: Ensure students attendance with various attendance marking modes',
      'Enhanced Safety: Emergency response and improved security for a safer commute'
    ],
    features: [
      'Live video surveillance',
      'Driver behavior monitoring',
      'Student attendance monitoring',
      'Bulk trip scheduling',
      'Emergency & SOS button',
      'Geofencing for safe zone alerts',
      'Transport tariff',
      'Instant notifications',
      'Fleet maintenance & health monitoring',
      'Detailed reports & analytics'
    ]
  },
  {
    id: 'employee-transportation',
    title: 'Employee Transportation Management',
    slug: 'employee-transportation',
    shortDescription: 'Simplifies corporate commuting by automating scheduling, optimizing routes and ensuring on-time arrivals.',
    content: [
      'Employee pickups & drops: Streamline better employee pickups and drops',
      'On-time arrivals: Punctual employee commutes with real-time vehicle tracking and live ETAs',
      'Smooth operations: Verified check-ins, driver authentication, and emergency support',
      'Reports & analytics: Detailed trip reports, vehicle analytics and performance tracking',
      'Optimized routing: Reduce travel time and fuel costs with smart route planning'
    ],
    features: [
      'Real-time tracking',
      'Automated employee attendance',
      'Leave management',
      'Geofencing & secure zone alerts',
      'Fleet health monitoring',
      'Female safety compliance',
      'Alerts & notifications',
      'Two-way communication',
      'Instant support system',
      'Expense management'
    ]
  },
  {
    id: 'field-employee-task',
    title: 'Field Employee Task Monitoring Software',
    slug: 'field-employee-task-monitoring',
    shortDescription: 'TaskEye is a solution for workforce management with task assignments, tracking employee activities, and coordination.',
    content: [
      'No forced hardware: Enjoy flexibility without being forced to use specific hardware',
      'End-to-end task management: Get full control from task creation to real-time updates',
      'Customizable workflow: Adapts to various industries, ensuring seamless task management',
      'User-friendly interface: Simple interface to make it easy for everyone, no need for extensive training'
    ],
    features: [
      'Task assignment & monitoring',
      'Attendance & shift management',
      'Geofencing',
      'Expense management',
      'Alert notifications',
      'Performance & productivity analytics',
      'Offline mode support',
      'SOS & emergency support',
      'Unlimited custom forms',
      'Timezone coordination'
    ]
  },
  {
    id: 'pet-monitoring',
    title: 'Pet Monitoring Software',
    slug: 'pet-monitoring',
    shortDescription: 'Comprehensive solution to track pet location, monitor health, and ensure safety.',
    content: [
      'Multi-pet dashboard: Manage multiple pets from a single account',
      'Geofencing alerts: Set safe zones and receive notifications when pets leave predefined areas',
      'Health & activity scoring: Calculates activity-rest balance for daily pet health insights',
      'Calories & distance tracking: Estimates calories burned based on pet weight, activity and rest time',
      'Integrated navigation: "Find My Pet" feature to navigate a lost pet location'
    ],
    features: [
      'Real-time pet location tracking',
      'Safe zone & geofence alerts',
      'Activity tracking & scoring',
      'Distance covered analysis',
      'Profile management',
      'Multi-pet management',
      'Last updated location',
      'Calories tracking',
      'Set activity goals',
      'Monthly activity comparison'
    ]
  },
  {
    id: 'indoor-tracking',
    title: 'Indoor Tracking Software',
    slug: 'indoor-tracking',
    shortDescription: 'Helps businesses monitor and manage assets, people, or inventory within defined indoor spaces.',
    content: [
      'Provides real-time location data, enhances security, and optimizes operational efficiency within large or complex environments.',
      'Uses technologies like Wi-Fi, Bluetooth, and RFID.'
    ],
    features: [
      'Real-time indoor location tracking',
      'Heatmap analysis & reporting',
      'Seamless integration',
      'Customized alerts',
      'Temperature monitoring',
      'Indoor-fencing',
      'User access control',
      'Wi-Fi and Bluetooth positioning system',
      'SOS for emergency',
      'Multi-storeyed tracking'
    ]
  }
];
